#FOR LOOP
for i in range(10):
    print(i,end=" ")
print()    
#list in loop
L=[21,12,18,"PYTHON",True,0.001,20]
for i in L:
    print(i,end=" ")
print()    
#set in loop
S={1,12,18,5j,"C++",False,101}
for i in S:
    print(i,end=" ")  
print()    
#tuple in loop
T=[51,21,31,41,7j,"JAVA",222]
for i in T:
    print(T,end=" ")
print()    
#dictonary in loop
D={1:'Jana',2:'Niranjan',3:'Sanjay',4j:'Krishna'}
for i,j in D.items():
    print(i,j,end=" ")   
print()    
for i in D.keys():
    print(i,end=" ")
print()    
for j in D.values():
    print(j,end=" ")   
print()            
